version: "3"

networks:
  proxy:
    external: true


services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    networks:
       - proxy
#       - default
#    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.websecure.address=:443"
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Port für das Traefik-Dashboard
    volumes:
      - "./certs:/certs"
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  whoami0:
    image: "traefik/whoami"
    container_name: whoami0
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      - "traefik.http.routers.whoami0-http.entrypoints=web"
      - "traefik.http.routers.whoami0-http.rule=Host(`whoami0.aci.lan`)"



  whoami1:
    image: "traefik/whoami"
    container_name: whoami1
    ports:
      - 8880:80
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      - "traefik.http.routers.whoami1-http.entrypoints=web"
      - "traefik.http.routers.whoami1-http.rule=Host(`whoami1.aci.lan`)"

      - traefik.http.services.whoami1-http.loadbalancer.server.port=80


  whoami2:
    networks:
       - proxy
    image: traefik/whoami
    container_name: whoami2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      - "traefik.http.routers.whoami2-https.entrypoints=websecure"
      - "traefik.http.routers.whoami2-https.rule=Host(`whoami2.aci.lan`)"
      - "traefik.http.routers.whoami2-https.tls=true"




  whoami3:
    image: traefik/whoami
    container_name: whoami3
    networks:
       - proxy
    ports:
      - 8881:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      - "traefik.http.routers.whoami3-http.entrypoints=web"
      - "traefik.http.routers.whoami3-http.rule=Host(`whoami3.aci.lan`)"
      
      - "traefik.http.routers.whoami3-https.entrypoints=websecure"
      - "traefik.http.routers.whoami3-https.rule=Host(`whoami3.aci.lan`)"
      - "traefik.http.routers.whoami3-https.tls=true"

      - traefik.http.services.whoami3-http.loadbalancer.server.port=80


  whoami4:
    image: traefik/whoami
    container_name: whoami4
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.whoami4-http.entrypoints=web"
      - "traefik.http.routers.whoami4-http.rule=Host(`whoami4.aci.lan`)"
      
      - "traefik.http.routers.whoami4-https.entrypoints=websecure"
      - "traefik.http.routers.whoami4-https.rule=Host(`whoami4.aci.lan`)"
      - "traefik.http.routers.whoami4-https.tls=true"

      - "traefik.http.routers.whoami4-http.middlewares=whoami4-redirect-https"
      - "traefik.http.middlewares.whoami4-redirect-https.redirectscheme.scheme=https"




  whoami5:
    image: traefik/whoami
    container_name: whoami5
    ports:
      - 8882:80
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.whoami5-http.entrypoints=web"
      - "traefik.http.routers.whoami5-http.rule=Host(`whoami5.aci.lan`)"
      
      - "traefik.http.routers.whoami5-https.entrypoints=websecure"
      - "traefik.http.routers.whoami5-https.rule=Host(`whoami5.aci.lan`)"
      - "traefik.http.routers.whoami5-https.tls=true"

      - "traefik.http.routers.whoami5-http.middlewares=whoami5-redirect-https"
      - "traefik.http.middlewares.whoami5-redirect-https.redirectscheme.scheme=https"

      - traefik.http.services.whoami5-http.loadbalancer.server.port=80



  whoami6:
    image: traefik/whoami
    container_name: whoami6
    ports:
      - 8883:80
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.whoami6-http.entrypoints=web"
      - "traefik.http.routers.whoami6-http.rule=Host(`whoami6.aci.lan`)"

      - "traefik.http.routers.whoami6-https.entrypoints=websecure"
      - "traefik.http.routers.whoami6-https.rule=Host(`whoami6.aci.lan`)"
      - "traefik.http.routers.whoami6-https.tls=true"

      - "traefik.http.routers.whoami6-http.middlewares=whoami6-redirect-https"
      - "traefik.http.middlewares.whoami6-redirect-https.redirectscheme.scheme=https"

      - traefik.http.services.whoami6-http.loadbalancer.server.port=80


